print('gegevens invoer')
name = input('geef uw naam ')
adress = input('geef uw adres ')
postal = input('geef uw postcode ')
residence = input('geef uw woonplaats ')
print('---------------------------------------------')
print('|naam                : ' + name)
print('|adres               : ' + adress)
print('|postcode            : ' + postal)
print('|woonplaats          : ' + residence)
print('---------------------------------------------')